Bioio
qupath/qubalab pull request #20
Opened 2024-10-29 10:54 UTC by alanocallaghan

2024-10-29 12:11 UTC, alanocallaghan commented
I added the zarr bit as a dependency but we should probably add a unit test for that

2024-10-30 19:11 UTC, alanocallaghan commented
Should we also add CZI? https://github.com/bioio-devs/bioio-czi

2024-11-04 14:01 UTC, Rylern requested changes

2024-11-04 14:03 UTC, Rylern commented
> We may want to add other plugins, or at least ensure users can add other plugins if they want. Maybe optional deps?
eg, https://github.com/bioio-devs/bioio-czi

Isn't `pip install bioio-czi` enough to add a new plugin (from the user perspective)?

2024-11-04 15:35 UTC, alanocallaghan commented
> Isn't pip install bioio-czi enough to add a new plugin (from the user perspective)?

Seems that way yeah. I'm happy sticking with the two OME formats by default.

2024-11-04 15:44 UTC, Rylern approved these changes

2024-11-04 15:58 UTC, merged